"""
base_model.py — Abstract Base Class for All ML/DL Models
==========================================================
Adaptive AI for Cyber Threat Detection

Defines the contract that every threat detection model must implement.
This enforces a consistent interface across all 4 detection modules,
enabling the Threat Fusion Engine (Module 10) to call any model
through a unified API.

Design Patterns:
  - Template Method: base class defines the algorithm skeleton
  - Abstract Factory: each detector module creates its own model variants
  - Strategy: models are interchangeable behind the same interface

SOLID Principles:
  - Interface Segregation: models only implement what they need
  - Dependency Inversion: high-level modules depend on this abstraction
  - Open/Closed: new models extend this base without modifying it

IEEE 29148 FR Reference: FR-MDL-001 through FR-MDL-006

Author: B.Tech Capstone Project
"""

import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

import numpy as np
from numpy.typing import NDArray

from src.core.constants import ModelAlgorithm, ThreatType
from src.core.exceptions import ModelInferenceError, ModelNotTrainedError
from src.core.logger import get_logger, get_model_logger

logger = get_logger(__name__)
model_logger = get_model_logger()


# =============================================================================
# Prediction Result Data Classes
# =============================================================================

@dataclass
class PredictionResult:
    """Encapsulates the output of a single model prediction.

    Immutable by convention — create a new instance rather than mutating.

    Attributes:
        threat_type: The category of threat detected.
        is_threat: True if the model classifies this as a threat.
        probability: Confidence score in [0.0, 1.0].
        risk_score: Weighted risk score used by the Fusion Engine.
        model_name: Name of the model that produced this result.
        algorithm: The ML algorithm used.
        inference_time_ms: Latency of the prediction in milliseconds.
        raw_output: Raw model output for SHAP/LIME explainability.
        metadata: Any additional result context.
    """

    threat_type: ThreatType
    is_threat: bool
    probability: float
    risk_score: float
    model_name: str
    algorithm: ModelAlgorithm
    inference_time_ms: float = 0.0
    raw_output: Optional[NDArray] = None
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Validate result fields after initialisation.

        Raises:
            ValueError: If probability or risk_score are outside [0, 1].
        """
        if not (0.0 <= self.probability <= 1.0):
            raise ValueError(
                f"probability must be in [0.0, 1.0], got {self.probability}"
            )
        if not (0.0 <= self.risk_score <= 1.0):
            raise ValueError(
                f"risk_score must be in [0.0, 1.0], got {self.risk_score}"
            )

    def to_dict(self) -> dict[str, Any]:
        """Serialise the result to a JSON-serialisable dictionary.

        Returns:
            Dictionary representation of the prediction result.
        """
        return {
            "threat_type": self.threat_type.value,
            "is_threat": self.is_threat,
            "probability": round(self.probability, 4),
            "risk_score": round(self.risk_score, 4),
            "model_name": self.model_name,
            "algorithm": self.algorithm.value,
            "inference_time_ms": round(self.inference_time_ms, 2),
            "metadata": self.metadata,
        }


@dataclass
class ModelMetrics:
    """Stores evaluation metrics for a trained model.

    Generated by evaluate() and persisted to the database for
    the Model Performance dashboard panel.

    Attributes:
        model_name: Identifier of the evaluated model.
        algorithm: Algorithm used.
        accuracy: Classification accuracy.
        precision: Weighted precision.
        recall: Weighted recall.
        f1_score: Weighted F1 score.
        roc_auc: Area under ROC curve.
        training_samples: Number of training samples used.
        test_samples: Number of test samples used.
        training_time_seconds: Total training duration.
        cv_scores: Cross-validation score array.
        confusion_matrix: Numpy confusion matrix.
        timestamp: ISO format timestamp of evaluation.
    """

    model_name: str
    algorithm: ModelAlgorithm
    accuracy: float = 0.0
    precision: float = 0.0
    recall: float = 0.0
    f1_score: float = 0.0
    roc_auc: float = 0.0
    training_samples: int = 0
    test_samples: int = 0
    training_time_seconds: float = 0.0
    cv_scores: Optional[NDArray] = None
    confusion_matrix: Optional[NDArray] = None
    timestamp: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Serialise metrics to a JSON-serialisable dictionary."""
        return {
            "model_name": self.model_name,
            "algorithm": self.algorithm.value,
            "accuracy": round(self.accuracy, 4),
            "precision": round(self.precision, 4),
            "recall": round(self.recall, 4),
            "f1_score": round(self.f1_score, 4),
            "roc_auc": round(self.roc_auc, 4),
            "training_samples": self.training_samples,
            "test_samples": self.test_samples,
            "training_time_seconds": round(self.training_time_seconds, 2),
            "cv_mean": float(np.mean(self.cv_scores)) if self.cv_scores is not None else None,
            "cv_std": float(np.std(self.cv_scores)) if self.cv_scores is not None else None,
            "timestamp": self.timestamp,
        }


# =============================================================================
# Abstract Base Model
# =============================================================================

class BaseDetectionModel(ABC):
    """Abstract base class for all threat detection models.

    Defines the complete interface contract:
      - train(X, y) — fit the model to labelled data
      - predict(X) — return prediction with probability
      - evaluate(X, y) — return ModelMetrics
      - save(path) — persist model artifacts to disk
      - load(path) — restore model artifacts from disk

    Every concrete model class (e.g., PhishingDistilBERT, URLXGBoost)
    must implement all abstract methods.

    Attributes:
        model_name: Human-readable model identifier.
        threat_type: The ThreatType this model detects.
        algorithm: The ML algorithm used.
        is_trained: Whether the model has been fitted.
        _model: The underlying sklearn/PyTorch model object.
        _metrics: Latest evaluation metrics.
    """

    def __init__(
        self,
        model_name: str,
        threat_type: ThreatType,
        algorithm: ModelAlgorithm,
    ) -> None:
        """Initialise the base model.

        Args:
            model_name: Human-readable identifier, e.g. "phishing_distilbert_v1".
            threat_type: The threat category this model detects.
            algorithm: The algorithm type for registry and logging.
        """
        self.model_name = model_name
        self.threat_type = threat_type
        self.algorithm = algorithm
        self.is_trained: bool = False
        self._model: Any = None
        self._metrics: Optional[ModelMetrics] = None

        model_logger.info(
            "Model initialised: %s | Algorithm: %s | Threat: %s",
            self.model_name,
            self.algorithm.value,
            self.threat_type.value,
        )

    # -------------------------------------------------------------------------
    # Abstract Methods (must be implemented by every concrete model)
    # -------------------------------------------------------------------------

    @abstractmethod
    def train(
        self,
        X_train: Any,
        y_train: Any,
        X_val: Optional[Any] = None,
        y_val: Optional[Any] = None,
    ) -> "BaseDetectionModel":
        """Train the model on labelled data.

        Args:
            X_train: Training features (numpy array, DataFrame, or token IDs).
            y_train: Training labels.
            X_val: Optional validation features for early stopping.
            y_val: Optional validation labels.

        Returns:
            Self — enables method chaining: model.train(X, y).evaluate(X_test, y_test)

        Raises:
            ModelTrainingError: If training fails.
        """
        ...

    @abstractmethod
    def predict(self, X: Any) -> PredictionResult:
        """Run inference on a single input and return a structured result.

        Args:
            X: Input features (single sample).

        Returns:
            PredictionResult with threat probability and risk score.

        Raises:
            ModelNotTrainedError: If model has not been trained.
            ModelInferenceError: If inference fails.
        """
        ...

    @abstractmethod
    def predict_batch(self, X: Any) -> list[PredictionResult]:
        """Run inference on a batch of inputs.

        Args:
            X: Batch of input features.

        Returns:
            List of PredictionResult, one per input sample.

        Raises:
            ModelNotTrainedError: If model has not been trained.
            ModelInferenceError: If inference fails.
        """
        ...

    @abstractmethod
    def evaluate(self, X_test: Any, y_test: Any) -> ModelMetrics:
        """Evaluate the model and return comprehensive metrics.

        Must compute: accuracy, precision, recall, F1, ROC-AUC,
        confusion matrix, and cross-validation scores.

        Args:
            X_test: Test features.
            y_test: True labels.

        Returns:
            ModelMetrics dataclass with all evaluation results.

        Raises:
            ModelNotTrainedError: If model has not been trained.
        """
        ...

    @abstractmethod
    def save(self, path: Path) -> Path:
        """Persist model artifacts to disk.

        Args:
            path: Directory where artifacts should be saved.

        Returns:
            Absolute path where the model was saved.

        Raises:
            IOError: If the save operation fails.
        """
        ...

    @abstractmethod
    def load(self, path: Path) -> "BaseDetectionModel":
        """Load model artifacts from disk.

        Args:
            path: Path to the saved model directory or file.

        Returns:
            Self — the loaded model instance.

        Raises:
            ModelNotFoundError: If the artifact path does not exist.
        """
        ...

    # -------------------------------------------------------------------------
    # Concrete Methods (shared behaviour — subclasses can override if needed)
    # -------------------------------------------------------------------------

    def _assert_trained(self) -> None:
        """Assert the model is trained before inference.

        Raises:
            ModelNotTrainedError: If is_trained is False.
        """
        if not self.is_trained:
            raise ModelNotTrainedError(self.model_name)

    def _timed_predict(self, X: Any) -> tuple[Any, float]:
        """Execute the internal prediction and measure latency.

        This helper wraps the raw model call with timing instrumentation.
        Subclasses should call this inside their predict() implementation
        rather than calling the model directly.

        Args:
            X: Input features.

        Returns:
            Tuple of (raw_prediction, latency_ms).
        """
        start = time.perf_counter()
        result = self._model_predict(X)
        elapsed_ms = (time.perf_counter() - start) * 1000.0
        model_logger.debug(
            "Inference completed: model=%s | latency=%.2fms",
            self.model_name,
            elapsed_ms,
        )
        return result, elapsed_ms

    def _model_predict(self, X: Any) -> Any:
        """Execute the underlying model prediction.

        Default implementation calls self._model.predict_proba(X).
        Deep learning models override this method.

        Args:
            X: Input features.

        Returns:
            Raw model output (probabilities or logits).

        Raises:
            ModelInferenceError: If prediction throws an exception.
        """
        try:
            return self._model.predict_proba(X)
        except Exception as exc:
            raise ModelInferenceError(
                model_name=self.model_name,
                reason=str(exc),
            ) from exc

    def get_metrics(self) -> Optional[ModelMetrics]:
        """Return the latest evaluation metrics, if available.

        Returns:
            ModelMetrics instance or None if evaluate() has not been called.
        """
        return self._metrics

    def __repr__(self) -> str:
        """Return a developer-friendly string representation."""
        return (
            f"{self.__class__.__name__}("
            f"name={self.model_name!r}, "
            f"algorithm={self.algorithm.value!r}, "
            f"threat={self.threat_type.value!r}, "
            f"trained={self.is_trained})"
        )
